#!/bin/zsh

# Configure history
HISTFILE=~/.cache/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
setopt share_history
setopt extended_history
setopt hist_ignore_space
setopt hist_ignore_all_dups

# Zinit - add plugins 
source /usr/share/zinit/zinit.zsh # using zinit AUR package

zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

zinit snippet OMZP::sudo
zinit snippet OMZP::command-not-found

# Load and style completions
autoload -Uz compinit && compinit 
zinit cdreplay -q

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# Configure other zsh options
setopt autocd
bindkey -v
bindkey '^ ' autosuggest-accept
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey -a 'k' history-search-backward
bindkey -a 'j' history-search-forward

# set prompt, use builtin for tty, else oh-my-posh
case $(tty) in 
  (/dev/tty[1-9]) autoload -Uz promptinit && promptinit && prompt adam1;; 
              (*) eval "$(oh-my-posh init zsh --config ~/.config/posh/catppuccin.json)";; 
esac

# Aliases
alias ls='ls -h --color=auto'
alias ll='ls -hl --color=auto'
alias la='ls -hlA --color=auto'
alias grep='grep --color=auto'
alias cat='bat'
alias vim='nvim'
alias vi='vim'

# Export envs
export EDITOR=nvim
export VISUAL=nvim
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

# Shell integrations
source <(fzf --zsh)

# New terminal window display
fastfetch --config ~/.config/fastfetch/init.jsonc
